### ISSUE TITLE
Instrumented tests - JUnit5Runner initialization error

### ISSUE THREAD

**Issue by Mugurell** [mannodermaus/android-junit5#139]
> $ adb shell am instrument -w -r   -e debug false -e runnerBuilder de.mannodermaus.junit5.AndroidJUnit5Builder -e class 'com.petrulingurar.movies.TestRunningOnJUnit5' com.example.petrulingurar.movies.debug.test/androidx.test.runner.AndroidJUnitRunner
> Client not ready yet..
> Started running tests
> 
> ```
> java.lang.BootstrapMethodError: Exception from call site #433 bootstrap method
> at org.junit.platform.launcher.core.ServiceLoaderTestEngineRegistry.loadTestEngines(ServiceLoaderTestEngineRegistry.java:37)
> at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:87)
> at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:67)
> at org.junit.platform.runner.JUnitPlatform.<init>(JUnitPlatform.java:119)
> at de.mannodermaus.junit5.AndroidJUnit5.<init>(Runner.kt:17)
> at de.mannodermaus.junit5.RunnerKt.createJUnit5Runner(Runner.kt:22)
> at de.mannodermaus.junit5.AndroidJUnit5Builder.runnerForClass(RunnerBuilder.kt:69)
> at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
> at androidx.test.internal.runner.AndroidRunnerBuilder.runnerForClass(AndroidRunnerBuilder.java:147)
> at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
> at androidx.test.internal.runner.TestLoader.doCreateRunner(TestLoader.java:73)
> at androidx.test.internal.runner.TestLoader.getRunnersFor(TestLoader.java:104)
> at androidx.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:789)
> at androidx.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:543)
> at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:386)
> at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
> Caused by: java.lang.ClassCastException: Bootstrap method returned null
> ... 16 more
> ```
> 
> Tests ran to completion.

Sample project - https://github.com/Mugurell/Movies-MVVM
The behaviour seems erratic, same tests in same configuration worked a few days ago. After they initially refused (same error). Now they error again.
Plugin version 1.3.2
JUnit5 version 5.3.2
testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
JUnit4 tests run ok, JUnit5 tests in the minApi 26 flavor are giving this error when run from the IDE or from Gradle.

**Comment by Mugurell** [comment]
Please ignore.
The problem was I was using v 1.3.1.1 when adding to classpath and v 1.3.2 for the dependencies

Thanks for your hard work!
