### ISSUE TITLE
android-junit5 1.3.2.0 fails to configure with jacoco-android

### ISSUE THREAD

**Issue by tnj** [mannodermaus/android-junit5#143]
When I try to activate android-junit5 1.3.2.0 with jacoco-android, Gradle fails to configure the project. 1.3.1.0 is working fine.

Environment: 
- Gradle 4.10.1
- Android Gradle Plugin 3.3.0 (also occures on 3.2.0)
- android-junit5 1.3.2.0
- jacoco-android 0.1.3

Error stacktrace(trimmed): 

```
Caused by: java.lang.NoSuchMethodError: org.gradle.testing.jacoco.tasks.JacocoReport.getExecutionData()Lorg/gradle/api/file/ConfigurableFileCollection;
        at de.mannodermaus.gradle.plugins.junit5.tasks.AndroidJUnit5JacocoReport.getExecutionData(Jacoco.kt:49)
        at de.mannodermaus.gradle.plugins.junit5.tasks.AndroidJUnit5JacocoReport_Decorated.getExecutionData(Unknown Source)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.getProperty(BeanDynamicObject.java:228)
        at org.gradle.internal.metaobject.BeanDynamicObject.tryGetProperty(BeanDynamicObject.java:171)
        at org.gradle.internal.metaobject.CompositeDynamicObject.tryGetProperty(CompositeDynamicObject.java:55)
        at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:59)
        at de.mannodermaus.gradle.plugins.junit5.tasks.AndroidJUnit5JacocoReport_Decorated.getProperty(Unknown Source)
        at de.mannodermaus.gradle.plugins.junit5.GroovyInterop.jacocoReportBase_executionData_setFrom(GroovyInterop.groovy:166)
        at de.mannodermaus.gradle.plugins.junit5.InteropKt.safeExecutionDataSetFrom(Interop.kt:38)
        at de.mannodermaus.gradle.plugins.junit5.tasks.AndroidJUnit5JacocoReport$ConfigAction.execute(Jacoco.kt:100)
        at de.mannodermaus.gradle.plugins.junit5.tasks.AndroidJUnit5JacocoReport$Companion$create$1.execute(Jacoco.kt:37)
        at de.mannodermaus.gradle.plugins.junit5.tasks.AndroidJUnit5JacocoReport$Companion$create$1.execute(Jacoco.kt:30)
        at org.gradle.api.internal.tasks.DefaultTaskContainer.create(DefaultTaskContainer.java:334)
        at de.mannodermaus.gradle.plugins.junit5.tasks.AndroidJUnit5JacocoReport$Companion.create(Jacoco.kt:36)
        at de.mannodermaus.gradle.plugins.junit5.AndroidJUnitPlatformPlugin$configureJacocoTasks$1.execute(Plugin.kt:97)
        at de.mannodermaus.gradle.plugins.junit5.AndroidJUnitPlatformPlugin$configureJacocoTasks$1.execute(Plugin.kt:21)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:158)
        at de.mannodermaus.gradle.plugins.junit5.AndroidJUnitPlatformPlugin.configureJacocoTasks(Plugin.kt:90)
        at de.mannodermaus.gradle.plugins.junit5.AndroidJUnitPlatformPlugin.access$configureJacocoTasks(Plugin.kt:21)
        at de.mannodermaus.gradle.plugins.junit5.AndroidJUnitPlatformPlugin$apply$3.execute(Plugin.kt:44)
        at de.mannodermaus.gradle.plugins.junit5.AndroidJUnitPlatformPlugin$apply$3.execute(Plugin.kt:21)
        at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingAction$1$1.run(DefaultListenerBuildOperationDecorator.java:155)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.reapply(DefaultUserCodeApplicationContext.java:58)
        at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingAction$1.run(DefaultListenerBuildOperationDecorator.java:152)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingAction.execute(DefaultListenerBuildOperationDecorator.java:149)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:91)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:80)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
        ... 114 more
```

**Comment by csschirag** [comment]
I am facing same issue.

**Comment by mannodermaus** [comment]
Thanks for reporting! Could you try this against the latest `1.3.2.1-SNAPSHOT`? The attempted backwards compatibility in the current version doesn't seem to catch the binary incompatibility in Gradle 5.

```groovy
buildscript {
  repositories {
    maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
  }
  dependencies {
    classpath "de.mannodermaus.gradle.plugins:android-junit5:1.3.2.1-SNAPSHOT"
  }
}
```

**Comment by murrcha** [comment]
Hi, @mannodermaus 
Say, please, where get new version (1.4.0.0)? Without this bug.
At Maven repository (mvnrepository.com) this version is not available

**Comment by tnj** [comment]
@mannodermaus Awesome, confirmed both `1.3.2.1-SNAPSHOT` and `1.4.0.0-SNAPSHOT` solve the problem 👍

**Comment by tnj** [comment]
@murrcha You need to add `maven {}` as @mannodermaus mentioned above

**Comment by murrcha** [comment]
> @murrcha You need to add `maven {}` as @mannodermaus mentioned above

Yes, this worked, thanks.

**Comment by murrcha** [comment]
> Hi, @mannodermaus
> Say, please, where get new version (1.4.0.0)? Without this bug.
> At Maven repository (mvnrepository.com) this version is not available

still actual

**Comment by mannodermaus** [comment]
Thanks for confirming! I wanted to get confirmation on this particular issue before publishing the artifact. Expect this to land within today.

**Comment by mannodermaus** [comment]
`1.4.0.0` is now released to jcenter. Thank you for your patience!
