### ISSUE TITLE
TestEngine with ID 'junit-vintage' failed to resolve AIDL class

### ISSUE THREAD

**Issue by goldy1992** [mannodermaus/android-junit5#157]
Here is a link to my gradle file that I'm currently working on https://github.com/goldy1992/Mp3Player/blob/feature/issue-31/use-mediastore-audio/app/build.gradle

As an overview:
1) WHEN I do a `gradle clean build` with `//apply plugin: "de.mannodermaus.android-junit5"` set in the apps `build.gradle` file ... I.e. the android-junit5 plugin NOT applied THEN only JUnit 4 tests run. I'm okay with this :-)

2) WHEN I do a `gradle clean build` with `apply plugin: "de.mannodermaus.android-junit5"` set in the apps `build.gradle` file ... I.e. the android-junit5 plugin IS applied THEN only JUnit5 tests run and from the gradle logs I see the following output:

```
> Task :app:testReleaseUnitTest

Gradle Test Executor 6 STANDARD_ERROR
    Mar 18, 2019 5:59:43 PM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
    WARNING: TestEngine with ID 'junit-vintage' failed to discover tests
    java.lang.NoClassDefFoundError: android/media/IAudioService
    	at java.lang.Class.getDeclaredMethods0(Native Method)
    	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
    	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
    	at java.lang.Class.privateGetPublicMethods(Class.java:2917)
    	at java.lang.Class.privateGetPublicMethods(Class.java:2917)
    	at java.lang.Class.getMethods(Class.java:1615)
    	at org.junit.platform.commons.util.ReflectionUtils.getDefaultMethods(ReflectionUtils.java:1335)
    	at org.junit.platform.commons.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:1308)
    	at org.junit.platform.commons.util.ReflectionUtils.findAllMethodsInHierarchy(ReflectionUtils.java:1250)
    	at org.junit.platform.commons.util.ReflectionUtils.findMethods(ReflectionUtils.java:1234)
    	at org.junit.platform.commons.util.ReflectionUtils.findMethods(ReflectionUtils.java:1220)
    	at org.junit.vintage.engine.descriptor.VintageTestDescriptor.toMethodSource(VintageTestDescriptor.java:167)
    	at org.junit.vintage.engine.descriptor.VintageTestDescriptor.toTestSource(VintageTestDescriptor.java:151)
    	at org.junit.vintage.engine.descriptor.VintageTestDescriptor.<init>(VintageTestDescriptor.java:55)
    	at org.junit.vintage.engine.discovery.TestClassRequestResolver.addChildrenRecursively(TestClassRequestResolver.java:110)
    	at org.junit.vintage.engine.discovery.TestClassRequestResolver.createCompleteRunnerTestDescriptor(TestClassRequestResolver.java:93)
    	at org.junit.vintage.engine.discovery.TestClassRequestResolver.determineRunnerTestDescriptor(TestClassRequestResolver.java:64)
    	at org.junit.vintage.engine.discovery.TestClassRequestResolver.createRunnerTestDescriptor(TestClassRequestResolver.java:59)
    	at org.junit.vintage.engine.discovery.VintageDiscoverer.lambda$discover$0(VintageDiscoverer.java:53)
    	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    	at java.util.Iterator.forEachRemaining(Iterator.java:116)
    	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
    	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
    	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742)
    	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
    	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
    	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
    	at org.junit.vintage.engine.discovery.VintageDiscoverer.discover(VintageDiscoverer.java:55)
    	at org.junit.vintage.engine.VintageTestEngine.discover(VintageTestEngine.java:62)
    	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:177)
    	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:164)
    	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
    	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:92)
    	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$100(JUnitPlatformTestClassProcessor.java:77)
    	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:73)
    	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
    	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    	at com.sun.proxy.$Proxy2.stop(Unknown Source)
    	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:131)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
    	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
    	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
    	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:3)
    	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
    	at java.lang.Thread.run(Thread.java:748)
    Caused by: java.lang.ClassNotFoundException: android.media.IAudioService
    	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    	... 67 more


Gradle Test Executor 6 finished executing tests.
```

I believe this to be stopping the JUnit 4 tests from running however when I don't use android-junt5 plugin they run fine.

Here is quick overview of my test dependencies:

```
    //vintage
    testImplementation group: 'junit', name: 'junit', version: JUNIT4_VERSION
    // (Optional) If you also have JUnit 4-based tests
    testRuntimeOnly group: 'org.junit.vintage', name: 'junit-vintage-engine', version: JUNIT5_VERSION
    // jupiter
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: JUNIT5_VERSION
    // (Required) Writing and executing Unit Tests on the JUnit Platform
    testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: JUNIT5_VERSION
    // JUnit Platform Launcher + Console
    testRuntimeOnly group: 'org.junit.platform', name: 'junit-platform-launcher', version: JUNIT_PLATFORM_VERSION
    testRuntimeOnly group: 'org.junit.platform', name: 'junit-platform-console', version: JUNIT_PLATFORM_VERSION
    //testImplementation group: 'org.mockito', name: 'mockito-junit-jupiter', version: '2.25.1'
    testImplementation group: 'org.mockito', name: 'mockito-core', version: MOCKITO_CORE_VERSION
    testImplementation group: 'org.powermock', name: 'powermock-module-junit4', version: POWERMOCK_JUNIT4_VERSION
    testImplementation group: 'org.powermock', name: 'powermock-core', version: POWERMOCKITO_CORE_VERSION
    testImplementation group: 'org.powermock', name: 'powermock-api-mockito2', version: POWERMOCKITO_API_VERSION

    testImplementation group: 'org.robolectric', name: 'robolectric', version: ROBOELECTRIC_VERSION
    testImplementation group: 'androidx.test', name: 'core', version: TEST_CORE_VERSION
```
```
    def MOCKITO_CORE_VERSION = '2.25.1'
    def POWERMOCK_JUNIT4_VERSION = '2.0.0'
    def JUNIT4_VERSION = '4.12'
    def JUNIT5_VERSION = '5.4.1'
    def JUINT_EXT_VERSION = '1.1.0'
    def JUNIT_PLATFORM_VERSION = '1.4.1'
    def POWERMOCKITO_CORE_VERSION = '2.0.0'
    def POWERMOCKITO_API_VERSION = '2.0.0'
    def ROBOELECTRIC_VERSION = '4.2.1'
    def TEST_CORE_VERSION = '1.1.0'
```
also android gradle plugin version is `3.3.2`
using gradle version `4.10.3`
android-junit5 version `1.4.0.0`

**Comment by mannodermaus** [comment]
Thanks for the detailed info and the report! Looks like you're making heavy use of Robolectric in your project, which necessitates the use of JUnit Vintage - from a setup point of view, your dependencies look fine (you can get rid of `junit-platform-launcher` and `junit-platform-console`, though - those shouldn't be necessary anymore).

You're experiencing a ClassNotFound exception on a framework interface, which I believe to be written in AIDL. It's possible that these generated interfaces are somehow missing from the classpath, which will lead to this error. The JUnit 5 plugin has been using the actual test tasks generated by the AGP for a while now, so it's slightly surprising that JUnit Vintage would trip over this class. Let me investigate some more! In the meantime, you could consider disabling the android-junit5 plugin for now, and using `junit-platform-runner` instead to run your JUnit 5 unit tests with JUnit 4 until this is resolved.

**Comment by mannodermaus** [comment]
I've been trying to replicate this in a test project, but don't seem to be able to. It's definitely possible that the combination of Robolectric, Powermock, Mockito and JUnit Vintage produces some kind of incompatibility. If it's possible for you to comment out your JUnit 4 test classes, trying to find a singular culprit which trips up test discovery, that would help quite a bit. I'm also going to try to find something in the codebase.

**Comment by mannodermaus** [comment]
After copying your test codebase, I am able to reproduce the behavior you described. Furthermore, inclusion of the android-junit5 plugin seems unrelated to the error - even if you just enable `useJUnitPlatform()` on the test tasks without the plugin, the same problem occurs.

**Comment by goldy1992** [comment]
@mannodermaus thank you so much for your help. 
I'll give this a try and let you know how I get on.
