### ISSUE TITLE
Failure with Android Gradle Plugin 3.6.0-alpha05

### ISSUE THREAD

**Issue by ashdavies** [mannodermaus/android-junit5#180]
After upgrading to the Android Gradle Plugin we're getting a failure for Gradle tasks when attempting to retrieve artifcats with `InternalArtifactType`.

```
Caused by: groovy.lang.MissingMethodException: No signature of method: com.android.build.gradle.internal.scope.VariantBuildArtifactsHolder.hasArtifact() is applicable for argument types: (com.android.build.gradle.internal.scope.InternalArtifactType) values: [JAVAC]
        at de.mannodermaus.gradle.plugins.junit5.GroovyInterop.variantScope_getJavacArtifactFiles(GroovyInterop.groovy:44)
        at de.mannodermaus.gradle.plugins.junit5.InteropKt.getSafeJavacArtifactFiles(Interop.kt:21)
        at de.mannodermaus.gradle.plugins.junit5.providers.JavaDirectoryProvider.classFoldersOf(Java.kt:28)
        at de.mannodermaus.gradle.plugins.junit5.providers.JavaDirectoryProvider.mainClassDirectories(Java.kt:17)
        at de.mannodermaus.gradle.plugins.junit5.providers.BaseKt.mainClassDirectories(Base.kt:50)
        at de.mannodermaus.gradle.plugins.junit5.tasks.AndroidJUnit5JacocoReport$ConfigAction.execute(Jacoco.kt:91)
        at de.mannodermaus.gradle.plugins.junit5.tasks.AndroidJUnit5JacocoReport$Companion$create$1.execute(Jacoco.kt:39)
        at de.mannodermaus.gradle.plugins.junit5.tasks.AndroidJUnit5JacocoReport$Companion$create$1.execute(Jacoco.kt:31)
        at org.gradle.api.internal.tasks.DefaultTaskContainer.create(DefaultTaskContainer.java:360)
        at de.mannodermaus.gradle.plugins.junit5.tasks.AndroidJUnit5JacocoReport$Companion.create(Jacoco.kt:38)
        at de.mannodermaus.gradle.plugins.junit5.AndroidJUnitPlatformPlugin$configureJacocoTasks$1.execute(Plugin.kt:93)
        at de.mannodermaus.gradle.plugins.junit5.AndroidJUnitPlatformPlugin$configureJacocoTasks$1.execute(Plugin.kt:17)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:158)
        at de.mannodermaus.gradle.plugins.junit5.AndroidJUnitPlatformPlugin.configureJacocoTasks(Plugin.kt:86)
        at de.mannodermaus.gradle.plugins.junit5.AndroidJUnitPlatformPlugin.access$configureJacocoTasks(Plugin.kt:17)
        at de.mannodermaus.gradle.plugins.junit5.AndroidJUnitPlatformPlugin$apply$3.execute(Plugin.kt:40)
        at de.mannodermaus.gradle.plugins.junit5.AndroidJUnitPlatformPlugin$apply$3.execute(Plugin.kt:17)
        at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingAction$1$1.run(DefaultListenerBuildOperationDecorator.java:150)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.reapply(DefaultUserCodeApplicationContext.java:58)
        at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingAction$1.run(DefaultListenerBuildOperationDecorator.java:147)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingAction.execute(DefaultListenerBuildOperationDecorator.java:144)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:91)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:80)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
        at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:324)
        at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:234)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy25.afterEvaluate(Unknown Source)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$NotifyAfterEvaluate$1.execute(LifecycleProjectEvaluator.java:190)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$NotifyAfterEvaluate$1.execute(LifecycleProjectEvaluator.java:187)
        at org.gradle.api.internal.project.DefaultProject.stepEvaluationListener(DefaultProject.java:1416)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$NotifyAfterEvaluate.run(LifecycleProjectEvaluator.java:196)
        ... 114 more
```

**Comment by mannodermaus** [comment]
Yeah, I saw that as well, but you beat me to it when it comes to opening a ticket ;). You might get away with it by disabling the Jacoco task generation, though I haven't verified that yet. We'll need to find a new way of getting the inputs of these tasks, hopefully more reliably.

To disable Jacoco task generation, try this:
```kotlin
android {
  testOptions {
    junitPlatform.jacocoOptions.taskGenerationEnabled = false
  }
}
```

**Comment by autonomousapps** [comment]
We do use jacoco, so would rather not disable it 🙂

**Comment by mannodermaus** [comment]
This was addressed by #182. Could you try this on the latest `1.5.1.0-SNAPSHOT`?

**Comment by autonomousapps** [comment]
This does seem to resolve it. Thanks!

**Comment by mannodermaus** [comment]
1.5.1.0 is now available. Thanks again for reporting!
