### ISSUE TITLE
org.junit.runners.model.InvalidTestClassError

### ISSUE THREAD

**Issue by IAmDarush** [mannodermaus/android-junit5#247]
My instrumented tests run just fine on a real devices and emulators. However, when running the tests on Firebase Test Lab I get the following error each time:
```
org.junit.runners.model.InvalidTestClassError: Invalid test class 'com.myapp.ui.MainInstrumentedTest':
1. No runnable methods
at org.junit.runners.ParentRunner.validate(ParentRunner.java:525)
at org.junit.runners.ParentRunner.<init>(ParentRunner.java:92)
at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:74)
at androidx.test.internal.runner.junit4.AndroidJUnit4ClassRunner.<init>(AndroidJUnit4ClassRunner.java:43)
at androidx.test.internal.runner.junit4.AndroidJUnit4Builder.runnerForClass(AndroidJUnit4Builder.java:65)
at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:37)
at androidx.test.internal.runner.AndroidRunnerBuilder.runnerForClass(AndroidRunnerBuilder.java:153)
at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
at androidx.test.internal.runner.TestLoader.doCreateRunner(TestLoader.java:73)
at androidx.test.internal.runner.TestLoader.getRunnersFor(TestLoader.java:105)
at androidx.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:804)
at androidx.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:575)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:393)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2209)

```

**Comment by mannodermaus** [comment]
When you explore the continuous integration pipeline for this project, you'll find that I also validate its instrumentation tests using Firebase Test Lab. This makes me wonder what could be the issue here...

Would you mind sharing how you submit your tests to it (obviously omitting the private stuff)? The thing is that you'll need to explicitly provide the configuration parameters to FTL, even though you already did it in your build.gradle file.

For reference, here's the excerpt from this project's CI script. Note the usage of `--environment-variables` and `test-runner-class`!

```
sudo gcloud firebase test android run \
  --type instrumentation \
  --app instrumentation/sample/build/outputs/apk/debug/sample-debug.apk \
  --test instrumentation/core/build/outputs/apk/androidTest/debug/core-debug-androidTest.apk \
  --environment-variables runnerBuilder=de.mannodermaus.junit5.AndroidJUnit5Builder \
  --test-runner-class androidx.test.runner.AndroidJUnitRunner \
  --device model=sailfish,version=28,locale=en_US,orientation=portrait \
  --results-bucket cloud-test-${GOOGLE_PROJECT_ID} \
  --timeout 15m
```

This should be covered in the wiki, I suppose. 🤔

**Comment by IAmDarush** [comment]
I'm using Android Studio (4.2)'s **Run/Debug Configurations** window and it looks like it is providing the configuration parameters correctly as I highlighted in green in the image.
![image](https://user-images.githubusercontent.com/22366924/114648032-ad738a00-9d10-11eb-83d2-132cc9df878a.png)

**Comment by IAmDarush** [comment]
Following is the configuration XML file. I suppose the **INSTRUMENTATION_RUNNER_CLASS** option should not be empty.

```

<component name="ProjectRunConfigurationManager">
  <configuration default="false" name="FirebaseTestLabTest" type="AndroidTestRunConfigurationType" factoryName="Android Instrumented Tests">
    <module name="Example.app" />
    <option name="TESTING_TYPE" value="2" />
    <option name="METHOD_NAME" value="" />
    <option name="CLASS_NAME" value="com.example.app.ui.MyInstrumentedTest" />
    <option name="PACKAGE_NAME" value="" />
    <option name="INSTRUMENTATION_RUNNER_CLASS" value="" />
    <option name="EXTRA_OPTIONS" value="" />
    <option name="INCLUDE_GRADLE_EXTRA_OPTIONS" value="true" />
    <option name="CLEAR_LOGCAT" value="false" />
    <option name="SHOW_LOGCAT_AUTOMATICALLY" value="false" />
    <option name="SKIP_NOOP_APK_INSTALLATIONS" value="true" />
    <option name="FORCE_STOP_RUNNING_APP" value="true" />
    <option name="TARGET_SELECTION_MODE" value="FIREBASE_DEVICE_MATRIX" />
    <option name="SELECTED_CLOUD_MATRIX_CONFIGURATION_ID" value="2147280645" />
    <option name="SELECTED_CLOUD_MATRIX_PROJECT_ID" value="my-project-id" />
    <option name="DEBUGGER_TYPE" value="Auto" />
    <Auto>
      <option name="USE_JAVA_AWARE_DEBUGGER" value="false" />
      <option name="SHOW_STATIC_VARS" value="true" />
      <option name="WORKING_DIR" value="" />
      <option name="TARGET_LOGGING_CHANNELS" value="lldb process:gdb-remote packets" />
      <option name="SHOW_OPTIMIZED_WARNING" value="true" />
    </Auto>
    <Hybrid>
      <option name="USE_JAVA_AWARE_DEBUGGER" value="false" />
      <option name="SHOW_STATIC_VARS" value="true" />
      <option name="WORKING_DIR" value="" />
      <option name="TARGET_LOGGING_CHANNELS" value="lldb process:gdb-remote packets" />
      <option name="SHOW_OPTIMIZED_WARNING" value="true" />
    </Hybrid>
    <Java />
    <Native>
      <option name="USE_JAVA_AWARE_DEBUGGER" value="false" />
      <option name="SHOW_STATIC_VARS" value="true" />
      <option name="WORKING_DIR" value="" />
      <option name="TARGET_LOGGING_CHANNELS" value="lldb process:gdb-remote packets" />
      <option name="SHOW_OPTIMIZED_WARNING" value="true" />
    </Native>
    <Profilers>
      <option name="ADVANCED_PROFILING_ENABLED" value="false" />
      <option name="STARTUP_PROFILING_ENABLED" value="false" />
      <option name="STARTUP_CPU_PROFILING_ENABLED" value="false" />
      <option name="STARTUP_CPU_PROFILING_CONFIGURATION_NAME" value="Sample Java Methods" />
      <option name="STARTUP_NATIVE_MEMORY_PROFILING_ENABLED" value="false" />
      <option name="NATIVE_MEMORY_SAMPLE_RATE_BYTES" value="2048" />
    </Profilers>
    <method v="2">
      <option name="Android.Gradle.BeforeRunTask" enabled="true" />
    </method>
  </configuration>
</component>
```

**Comment by IAmDarush** [comment]
I used your CI script to submit the tests and this time I got a more detailed error:

```
java.lang.IllegalStateException: junit-platform-runner not found on runtime classpath of instrumentation tests; please review your androidTest dependencies or raise an issue.
at de.mannodermaus.junit5.AndroidJUnit5Builder.runnerForClass(RunnerBuilder.kt:72)
at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
at androidx.test.internal.runner.AndroidRunnerBuilder.runnerForClass(AndroidRunnerBuilder.java:147)
at androidx.test.internal.runner.TestLoader$ScanningRunnerBuilder.runnerForClass(TestLoader.java:144)
at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
at androidx.test.internal.runner.TestLoader.doCreateRunner(TestLoader.java:73)
at androidx.test.internal.runner.TestLoader.getRunnersFor(TestLoader.java:105)
at androidx.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:804)
at androidx.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:575)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:393)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2189)
Caused by: java.lang.NoClassDefFoundError: org.junit.platform.launcher.core.ServiceLoaderTestEngineRegistry
at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:95)
at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:75)
at de.mannodermaus.junit5.AndroidJUnit5.<init>(AndroidJUnit5.java:52)
at de.mannodermaus.junit5.AndroidJUnit5.<init>(AndroidJUnit5.java:63)
at de.mannodermaus.junit5.HelpersKt.createJUnit5Runner(Helpers.kt:15)
at de.mannodermaus.junit5.AndroidJUnit5Builder.runnerForClass(RunnerBuilder.kt:68)
... 10 more
Caused by: java.lang.NoSuchMethodError: No static method newKeySet()Lj$/util/concurrent/ConcurrentHashMap$KeySetView; in class Lj$/util/concurrent/ConcurrentHashMap; or its super classes (declaration of 'j$.util.concurrent.ConcurrentHashMap' appears in /data/app/com.example.app.debug-wMAHOrPUar1ZlwkGaWpmtA==/base.apk!classes3.dex)
at org.junit.platform.commons.logging.LoggerFactory.<clinit>(LoggerFactory.java:36)
at org.junit.platform.commons.logging.LoggerFactory.getLogger(LoggerFactory.java:47)
at org.junit.platform.launcher.core.ServiceLoaderTestEngineRegistry.<clinit>(ServiceLoaderTestEngineRegistry.java:32)
... 16 more

```

**Comment by DanielAsher** [comment]
![Screenshot 2021-04-14 at 11 51 00](https://user-images.githubusercontent.com/7915553/114699146-d21f3000-9d17-11eb-870b-71d4adcda7c0.png)

**Comment by mannodermaus** [comment]
Both of you seem to execute the tests on API 29, whereas the default integration currently uses 28 - can you already tell I set this up a while ago? I'm wondering if it has something to do with the OS version. Would you mind re-running this on an API 28 device, please? I don't have immediate resources to attend to this right away but it might be good to gather as much info as possible.

Also, @IAmDarush, that `NoSuchMethodError` seems to indicate you're using core library desugaring, is that correct? It seems to look for `j$.util.concurrent.ConcurrentHashMap` and failing. I vaguely remember reading somewhere that desugaring & instrumentation tests on FTL don't work together very well, but I'm unable to find this resource again.

**Comment by IAmDarush** [comment]
@mannodermaus Yes we're using core library desugaring.

**Comment by IAmDarush** [comment]
Running the tests on API 28 resulted in a similar error:

![image](https://user-images.githubusercontent.com/22366924/115545667-a6cbb080-a2d6-11eb-8181-ea4b9a6e2377.png)

**Comment by IAmDarush** [comment]
I disabled core library desugaring and this time I'm getting a different error.

![image](https://user-images.githubusercontent.com/22366924/115546284-691b5780-a2d7-11eb-824a-e32a54d895cf.png)

**Comment by DanielAsher** [comment]
👍

**Comment by IAmDarush** [comment]
I've been recently in contact with the Firebase Support team and they suggested that I try running the tests on a **Physical Device** instead of a **Virtual Device** on FTL. Following are the results:

- With **coreLibraryDesugaringEnabled** on, the tests **failed**.

- With **coreLibraryDesugaringEnabled** off, the tests **passed**.

@mannodermaus as you suggested, it appears that, desugaring with instrumentation tests on FTL has been the cause of the issue. 

I've also reported the same results to the Firebase Support team and will report back here of any outcomes.

Thanks a lot.

**Comment by mannodermaus** [comment]
I'm looking forward to any future updates from the Firebase side - fingers are crossed that they'll be able to support core library desugaring soon. Until we have more insight, I'll close this ticket.
