### ISSUE TITLE
Build broken when using kotlin 1.7.21

### ISSUE THREAD

**Issue by doniwinata0309** [mannodermaus/android-junit5#286]
Hi, when using kotlin 1.7.21, junit5 return error:
java.io.File org.jetbrains.kotlin.gradle.tasks.KotlinCompile.getDestinationDir()

This is the complete stacktrace:
```
Caused by: java.lang.NoSuchMethodError: 'java.io.File org.jetbrains.kotlin.gradle.tasks.KotlinCompile.getDestinationDir()'
at de.mannodermaus.gradle.plugins.junit5.providers.KotlinDirectoryProvider.classFoldersOf(Kotlin.kt:42)
at de.mannodermaus.gradle.plugins.junit5.providers.KotlinDirectoryProvider.mainClassDirectories(Kotlin.kt:28)
at de.mannodermaus.gradle.plugins.junit5.providers.BaseKt.mainClassDirectories(Base.kt:50)
at de.mannodermaus.gradle.plugins.junit5.tasks.AndroidJUnit5JacocoReport$ConfigAction.execute(AndroidJUnit5JacocoReport.kt:86)
at de.mannodermaus.gradle.plugins.junit5.tasks.AndroidJUnit5JacocoReport$Companion$create$1.execute(AndroidJUnit5JacocoReport.kt:36)
at de.mannodermaus.gradle.plugins.junit5.tasks.AndroidJUnit5JacocoReport$Companion$create$1.execute(AndroidJUnit5JacocoReport.kt:28)
at org.gradle.api.internal.tasks.DefaultTaskContainer.create(DefaultTaskContainer.java:362)
at de.mannodermaus.gradle.plugins.junit5.tasks.AndroidJUnit5JacocoReport$Companion.create(AndroidJUnit5JacocoReport.kt:35)
at de.mannodermaus.gradle.plugins.junit5.AndroidJUnitPlatformPlugin$configureJacocoTasks$1.execute(Plugin.kt:141)
at de.mannodermaus.gradle.plugins.junit5.AndroidJUnitPlatformPlugin$configureJacocoTasks$1.execute(Plugin.kt:19)
at org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:123)
at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1.run(DefaultCollectionCallbackActionDecorator.java:110)
at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)```
```
Do you have idea how to fix this issue? Thank you in advance

**Comment by mannodermaus** [comment]
Please update the android-junit5 plugin to version `1.8.2.1` to use Kotlin 1.7 and beyond. [Here](https://github.com/mannodermaus/android-junit5/releases/tag/plugin-1.8.2.1) are the release notes for that version!
