### ISSUE TITLE
NoClassDefFoundError: org/jetbrains/kotlin/gradle/plugin/KotlinPluginKt with Kotlin 1.8.20

### ISSUE THREAD

**Issue by jscheibengruber** [mannodermaus/android-junit5#296]
I am getting this exception:
`Caused by: java.lang.NoClassDefFoundError: org/jetbrains/kotlin/gradle/plugin/KotlinPluginKt
        at de.mannodermaus.gradle.plugins.junit5.internal.providers.KotlinDirectoryProviderKt.getKotlin(KotlinDirectoryProvider.kt:63)
        at de.mannodermaus.gradle.plugins.junit5.internal.providers.KotlinDirectoryProviderKt.access$getKotlin(KotlinDirectoryProvider.kt:1)
        at de.mannodermaus.gradle.plugins.junit5.internal.providers.KotlinDirectoryProvider.sourceFoldersOf(KotlinDirectoryProvider.kt:35)
        at de.mannodermaus.gradle.plugins.junit5.internal.providers.KotlinDirectoryProvider.mainSourceDirectories(KotlinDirectoryProvider.kt:26)
        at de.mannodermaus.gradle.plugins.junit5.internal.providers.DirectoryProviderKt.mainSourceDirectories(DirectoryProvider.kt:53)
        at de.mannodermaus.gradle.plugins.junit5.tasks.AndroidJUnit5JacocoReport$ConfigAction.execute(AndroidJUnit5JacocoReport.kt:112)
        at org.gradle.api.internal.DefaultMutationGuard$2.execute(DefaultMutationGuard.java:44)
        at org.gradle.api.internal.DefaultMutationGuard$2.execute(DefaultMutationGuard.java:44)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:123)
        at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1.run(DefaultCollectionCallbackActionDecorator.java:110)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
        at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction.execute(DefaultCollectionCallbackActionDecorator.java:107)
        at org.gradle.internal.ImmutableActionSet$SetWithManyActions.execute(ImmutableActionSet.java:329)
        at org.gradle.api.internal.DefaultDomainObjectCollection.doAdd(DefaultDomainObjectCollection.java:262)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection.doAdd(DefaultNamedDomainObjectCollection.java:113)
        at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:256)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection$AbstractDomainObjectCreatingProvider.tryCreate(DefaultNamedDomainObjectCollection.java:944)
        ... 153 more
`

when running `gradle tasks` in our project. Seems like the root cause is that `KotlinPlugin` has been renamed `KotlinJVMPlugin` from Kotlin 1.7.x to 1.8.x. Seems they also consider this an internal class, which is not covered by their api-checker (found this: https://github.com/JetBrains/kotlin/tree/master/libraries/tools/kotlin-gradle-plugin-api)

**Comment by mannodermaus** [comment]
Hi, which version of the android-junit5 plugin are you using? It doesn't try to access this `KotlinPluginKt` class itself, however it's possible that there is a binary incompatibility with the transitive lookup that the plugin _does_ perform. Could I ask you to try the latest `1.9.0.0-SNAPSHOT` version? It changes the implementation of how source directories are retrieved for Java and Kotlin.

**Comment by vitorhugods** [comment]
Same issue here, using [Plugin 1.8.2.1](https://github.com/mannodermaus/android-junit5/releases/tag/plugin-1.8.2.1).

Confirmed that using `1.9.0.0-SNAPSHOT` contains a fix. I encourage you to give it a try @jscheibengruber.

**Comment by jscheibengruber** [comment]
Yes, we use the same version 1.8.2.1.
And I can also confirm that 1.9.0.0-SNAPSHOT fixes the issue.

**Comment by mannodermaus** [comment]
This is released in `1.9.3.0`!
