### ISSUE TITLE
Removed  junit5.unitTestsRuntime()?

### ISSUE THREAD

**Issue by autonomousapps** [mannodermaus/android-junit5#93]
I noticed you removed your recommendation to add this to an app's dependencies, but when I removed myself, I was no longer able to run JUnit5 tests from within Android Studio. Is there something I'm missing?

This is the error I got:
```
Exception in thread "main" java.lang.NoSuchMethodError: org.junit.platform.launcher.Launcher.execute(Lorg/junit/platform/launcher/LauncherDiscoveryRequest;)V
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:61)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
```

**Comment by autonomousapps** [comment]
Ah, I see this warning now:
```
AGBPI: {"kind": "warning","text":"The unitTestsRuntime() dependency has been deprecated with the stable release of Android Studio 3.1, and will be removed in a future release. Please go ahead, update your IDE & remove this dependency!"}
```
I'm still using AS 3.0, because 3.1 is giving me a major headache.
